name: fingSwipeV2
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter

  # DATA
  http: ^0.12.2
  provider: ^4.3.2+2
  shared_preferences: ^0.5.11
  flutter_launcher_icons: ^0.8.0

  # UX
  simple_gesture_detector: ^0.1.4

  # UI
  flutter_animation_progress_bar: ^1.0.5
  flutter_svg: ^0.19.0
  country_icons: ^1.1.1
  flutter_native_splash: ^0.1.9


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  # to update, run:
  # flutter pub run flutter_launcher_icons:main
  android: true
  ios: true
  image_path: "assets/logo_app_v2.png"


flutter_native_splash:
  # to run:
  # flutter pub pub run flutter_native_splash:create
  image: assets/splashscreen.png
  color: "FFFFFF"
  fill: true

flutter:
  uses-material-design: true

  assets:
    - assets/

